### ISSUE TITLE
Very slow (3-5 secs) on first deserialization, on Android

### ISSUE THREAD

**Issue by phucvin** [jacobdufault/fullinspector#143]
I use Full Inspector to edit static game data (i.e. heroes details, upgrades, ...), save it in scriptable object, and I load that data at start-up.
But it's very slow on Android device (medium specs), it took about 3-5 seconds to done reading the data, although the data is not large now, only about ~20KB in JSON text. And I used ProtoBuf too.

And I found out that maybe Full Inspector and BaseScriptableObject are the problem, not the serializer. I tested ProtoBuf and FullSerializer with in-memory data, also on same Android device, and they only took 100ms (ProtoBuf), 400ms (FullSerializer).

Note that the second time loading the same data from another scriptable object, in same game session, is very quick, only 20-40ms.

Is there anything you can do to reduce the time for fist deserialization? Because 3 seconds are long with my small game data (full game data can be 100x larger). And I think there is a way to improve it.

**Comment by jacobdufault** [comment]
That's really strange. I'll take a look.

**Comment by jacobdufault** [comment]
I've added some optimizations to a preview build available on [access](jacobdufault.github.io/fullinspector/access/). Please give that build a try and let me know if it helps. If loading is still excessively slow, please reopen. Thanks!

**Comment by phucvin** [comment]
Unfortunately, the loading time is the same.

I found that fiSettings has a static block, this block take about 600ms on my Android device. Maybe the assemblies traversing for finding fiSettingsProcesssor is a heavy reflection operation.

And how do you think about Mono JIT make the first time accessing to any code slow because of the Just-In-Time compiling?
I want to believe this but I tested with IL2CPP for Android, so there should be no more JIT, but the loading time is the same.

**Comment by jacobdufault** [comment]
I'm not sure of a way to setup settings without the current approach - the primary difficulty is because Full Inspector supports DLL builds.

If you're willing to do a source build, I've added `fiSettings.EnableSettingsProcessor`. Set that to false and then there will be no reflection inside of the `fiSettings` static constructor - however, if you have any `fiSettingsProcessor` instances that will stop working. This should remove that 600ms initialization block.

Accessing the code could for slow for any number of reasons - it's certainly possible the mono JIT compiler is running, but I'm not familiar with what style of JIT compiler it uses. The time here is almost certainly being dominated by reflection. I'll see what I can do to speed that bit up.
